# Generated by Django 4.2.5 on 2023-10-06 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('telefone', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_consulta', models.CharField(max_length=5)),
                ('observacao', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.convenio')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.procedimento')),
            ],
        ),
    ]
