# Generated by Django 4.2.5 on 2023-10-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_paciente_owner_alter_paciente_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hora_consulta',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
