# Generated by Django 4.2.5 on 2023-10-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_paciente_hora_consulta_alter_paciente_data_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateField(default='00/00/00'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='hora_consulta',
            field=models.TimeField(default='09:00'),
        ),
    ]
