# Generated by Django 4.2.5 on 2023-10-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_paciente_data_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
