# Generated by Django 4.2.5 on 2023-10-17 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_paciente_data_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.convenio'),
        ),
    ]
