# Generated by Django 4.2.5 on 2023-10-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_paciente_show_alter_paciente_convenio'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cep',
            field=models.CharField(blank=True, default='00000-000', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, default='Desconhecido', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, default='000000000-00', max_length=13),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paciente',
            name='endereco',
            field=models.CharField(blank=True, default='Desconhecido', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, default='Desconhecido', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_mae',
            field=models.CharField(blank=True, default='Desconhecido', max_length=55),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, default='000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo_biologico',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=10),
        ),
    ]
