# Generated by Django 4.2.5 on 2023-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_paciente_cep_paciente_cidade_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
