# Generated by Django 4.2.5 on 2023-10-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_paciente_bairro_paciente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
