# Generated by Django 4.2.5 on 2023-10-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_paciente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Cancelado', 'Cancelado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=20),
        ),
    ]
