# Generated by Django 4.2.5 on 2023-10-30 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_paciente_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queixa_principal', models.TextField(blank=True)),
                ('historia_molestia_atual', models.TextField(blank=True)),
                ('historico_e_antecedentes', models.TextField(blank=True)),
                ('exame_fisico', models.TextField(blank=True)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diagnostico', models.TextField(blank=True, max_length=50)),
                ('condutas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(blank=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='dashboard.atendimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.paciente')),
            ],
        ),
    ]
