# Generated by Django 4.2.5 on 2023-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_paciente_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.CharField(blank=True, default=18, max_length=2),
        ),
    ]
