# Generated by Django 4.2.5 on 2023-11-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_paciente_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.paciente'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='condutas',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='exame_fisico',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='historia_molestia_atual',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='historico_e_antecedentes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='queixa_principal',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
