# Generated by Django 4.2.5 on 2023-11-22 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_atendimento_paciente_alter_atendimento_condutas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.paciente'),
        ),
    ]
