# Generated by Django 4.2.5 on 2023-11-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_atendimento_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
