# Generated by Django 4.2.5 on 2023-12-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_atendimento_altura_alter_atendimento_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.paciente'),
        ),
    ]
