# Generated by Django 4.2.5 on 2024-01-15 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_atendimento_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='ano_atendimento',
            field=models.IntegerField(default=2023),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 15, 13, 51, 57, 928999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='mes_atendimento',
            field=models.IntegerField(default=1),
        ),
    ]
