# Generated by Django 4.2.5 on 2024-01-16 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_atendimento_ano_atendimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='data_consulta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hora_consulta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='status',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 13, 42, 25, 520554, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(default='0000-00-00')),
                ('hora_consulta', models.TimeField(default='09:00')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Cancelado', 'Cancelado'), ('Confirmado', 'Confirmado')], default='Pendente', max_length=20)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.procedimento')),
            ],
        ),
    ]
