# Generated by Django 4.2.5 on 2024-01-22 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_paciente_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 12, 22, 12, 74635, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo_biologico',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10),
        ),
    ]
