# Generated by Django 4.2.5 on 2024-01-22 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 12, 47, 37, 825971, tzinfo=datetime.timezone.utc)),
        ),
    ]
