# Generated by Django 4.2.5 on 2024-02-01 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 1, 11, 40, 13, 814817, tzinfo=datetime.timezone.utc)),
        ),
    ]
