# Generated by Django 4.2.5 on 2024-02-09 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alter_atendimento_data_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.date(2024, 2, 9)),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='total_anual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='total_diario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='total_mensal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.date(2024, 2, 9)),
        ),
    ]
