# Generated by Django 4.2.5 on 2024-02-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_agendamento_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
