# Generated by Django 4.2.5 on 2024-02-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_atendimento_atendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.agendamento'),
        ),
    ]
