# Generated by Django 4.2.5 on 2024-02-20 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_atendimento_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='agendamento',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.date(2024, 2, 20)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_atendimento',
            field=models.DateTimeField(default=datetime.date(2024, 2, 20)),
        ),
    ]
