# Generated by Django 4.2.5 on 2024-02-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_atendimento_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='agendamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.agendamento'),
        ),
    ]
