# Generated by Django 4.2.5 on 2024-02-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_alter_agendamento_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
    ]
