# Generated by Django 4.2.5 on 2024-02-26 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_atendimento_data_hora_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 22, 16, 180685, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.date(2024, 2, 26)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 12, 22, 16, 181704, tzinfo=datetime.timezone.utc)),
        ),
    ]
