# Generated by Django 4.2.5 on 2024-03-07 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_agendamento_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.date(2024, 3, 7)),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 11, 34, 52, 73838, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 14, 34, 52, 74837, tzinfo=datetime.timezone.utc)),
        ),
    ]
