# Generated by Django 4.2.5 on 2024-03-07 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_atendimento_editado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='editado',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 11, 36, 19, 51214, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 14, 36, 19, 52238, tzinfo=datetime.timezone.utc)),
        ),
    ]
