# Generated by Django 4.2.5 on 2024-03-08 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_agendamento_data_hora_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idade',
            field=models.CharField(blank=True, default=18, max_length=2),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.date(2024, 3, 8)),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 10, 50, 54, 348946, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 13, 50, 54, 349945, tzinfo=datetime.timezone.utc)),
        ),
    ]
