# Generated by Django 4.2.5 on 2024-03-12 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_remove_atendimento_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='valor_padrao',
            field=models.DecimalField(decimal_places=2, default=50.5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 8, 54, 54, 244268, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 11, 54, 54, 245264, tzinfo=datetime.timezone.utc)),
        ),
    ]
