# Generated by Django 4.2.5 on 2024-03-12 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_convenio_valor_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='n_reconsultas',
            field=models.CharField(default=3, max_length=10),
        ),
        migrations.AddField(
            model_name='convenio',
            name='prazo_reconsultas',
            field=models.CharField(default=15, max_length=30),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 9, 47, 33, 43172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 12, 47, 33, 44168, tzinfo=datetime.timezone.utc)),
        ),
    ]
