# Generated by Django 4.2.5 on 2024-03-14 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_convenio_owner_alter_agendamento_data_agendamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='shared_value',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Unimed', 'Unimed'), ('SUS', 'SUS')], default=[('Particular', 'Particular'), ('Unimed', 'Unimed'), ('SUS', 'SUS')], max_length=20),
        ),
        migrations.AddField(
            model_name='convenio',
            name='user_value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 10, 45, 15, 932908, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 13, 45, 15, 933884, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='valor_padrao',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
