# Generated by Django 4.2.5 on 2024-03-14 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_convenio_shared_value_convenio_user_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 10, 54, 51, 394130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 13, 54, 51, 394130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='shared_value',
            field=models.CharField(choices=[('Particular', 'Particular'), ('Unimed', 'Unimed'), ('SUS', 'SUS')], default='Particular', max_length=20),
        ),
    ]
