# Generated by Django 5.0.3 on 2024-03-18 15:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_alter_agendamento_data_hora_agendamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='user_value',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.convenio'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(default=datetime.date(2024, 3, 18)),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 12, 4, 18, 298606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.procedimento'),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 15, 4, 18, 298606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='queixa_principal',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Prontuario',
        ),
    ]
