# Generated by Django 5.0.3 on 2024-03-19 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_atendimento_valor_total_anual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_hora_agendamento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 12, 18, 53, 579467, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='data_hora_atendimento',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 18, 53, 580467, tzinfo=datetime.timezone.utc)),
        ),
    ]
