from .dashboard.v_index import *
from .agenda.v_agenda import *
from .pacientes.v_pacientes import *
from .prontuarios.v_prontuarios import *
from .configuracoes.v_configuracoes import *
from .relatorios.v_relatorios import *
from .pacientes.v_form_patient import *
from .prontuarios.v_prontuario import *
from .prontuarios.v_form_atendimento import *
from .usuarios.v_form_users import *
from .teste import *
from .usuarios.v_login_user import *
from .usuarios.v_logout_user import *
from .usuarios.v_update_user import *
from .pacientes.v_read_patient import *
from .agenda.v_form_agendamento import *