from .dashboard.v_index import *
from .v_agenda import *
from .pacientes.v_pacientes import *
from .prontuarios.v_prontuarios import *
from .v_configuracoes import *
from .v_relatorios import *
from .dashboard.v_form_patient import *
from .prontuarios.v_prontuario import *
from .prontuarios.v_form_atendimento import *